main: io.th0rgal.oraxen.OraxenPlugin
name: Oraxen
version: ${projectVersion}
author: Th0rgal
api-version: "1.18"
softdepend: [ ProtocolLib, LightAPI, PlaceholderAPI, MythicMobs, MMOItems, BossShopPro,
              CrateReloaded, ItemBridge, WorldGuard, Towny, Factions, Lands, NBTAPI ]
loadbefore: [ Realistic_World ]
