name: Publish project to Maven repository
# OR, publish per each commit
on:
  push:
    branches: [ master, develop ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew core:build core:publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }} # token name
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }} # token secret (password)
